version: "3"

dotenv: [".env"]

tasks:
  run:
    desc: Run the server
    cmds:
      - go run ./cmd/server

  build:
    desc: Build the server binary
    cmds:
      - go build -o bin/server ./cmd/server

  test:
    desc: Run tests
    cmds:
      - go test ./...

  fmt:
    desc: Format code
    cmds:
      - gofmt -w .

  tidy:
    desc: Tidy go.mod and go.sum
    cmds:
      - go mod tidy

  migrate:up:
    desc: Apply all migrations
    env:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "user={{.POSTGRES_USER}} password={{.POSTGRES_PASSWORD}} dbname={{.POSTGRES_DB}} sslmode=disable host=localhost port={{.POSTGRES_PORT}}"
    cmds:
      - goose -dir migrations up

  migrate:down:
    desc: Rollback the last migration
    env:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "user={{.POSTGRES_USER}} password={{.POSTGRES_PASSWORD}} dbname={{.POSTGRES_DB}} sslmode=disable host=localhost port={{.POSTGRES_PORT}}"
    cmds:
      - goose -dir migrations down

  migrate:status:
    desc: Show migration status
    env:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "user={{.POSTGRES_USER}} password={{.POSTGRES_PASSWORD}} dbname={{.POSTGRES_DB}} sslmode=disable host=localhost port={{.POSTGRES_PORT}}"
    cmds:
      - goose -dir migrations status

  proto:install:
    desc: Install protoc plugins (go, grpc, validate)
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - go install github.com/envoyproxy/protoc-gen-validate@latest

  proto:gen:
    desc: Generate gRPC code from proto files
    cmds:
      - mkdir -p pkg/grpc/gen
      - |
        GOPATH="$(go env GOPATH)"
        PGV_DIR="$GOPATH/pkg/mod/github.com/envoyproxy/$(ls "$GOPATH/pkg/mod/github.com/envoyproxy" | grep '^protoc-gen-validate@' | head -n1)"
        PROTOBUF_DIR="$GOPATH/pkg/mod/google.golang.org/$(ls "$GOPATH/pkg/mod/google.golang.org" | grep '^protobuf@' | head -n1)/src"
        if [ ! -d "$PROTOBUF_DIR" ]; then PROTOBUF_DIR="/usr/include"; fi
        PATH="$GOPATH/bin:$PATH" protoc -I api/proto -I "$PGV_DIR" -I "$PROTOBUF_DIR" \
          --go_out=pkg/grpc/gen --go_opt=paths=source_relative \
          --go-grpc_out=pkg/grpc/gen --go-grpc_opt=paths=source_relative \
          --validate_out=lang=go,paths=source_relative:pkg/grpc/gen \
          $(find api/proto -name '*.proto')

  grpc:stress:
    desc: Run high-load gRPC stress test (requires TASK_ID env).
    cmds:
      - |
        GRPC_TARGET=localhost:50051 \
        CONCURRENCY=128 \
        BATCH_SIZE=200 \
        DURATION_SEC=120 \
        TASK_ID=${TASK_ID} \
        node scripts/grpc_tools.js stress
